package hostimport

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/zsuroy/ctty/internal/config"
)

// Options controls writing parsed hosts into an OpenSSH include file.
type Options struct {
	Source     Source
	Data       []byte
	MainConfig string
	DestFile   string // empty → ~/.ssh/config.d/<source DestFileName>
	DryRun     bool
}

// Result summarizes what an import would do / did.
type Result struct {
	AddedCount   int
	SkippedCount int
	DestFile     string
	IncludeAdded bool
	Preview      string
}

// DefaultDestFile is <dir of main config>/config.d/<name>.
func DefaultDestFile(mainConfig, destName string) string {
	return filepath.Join(filepath.Dir(mainConfig), "config.d", destName)
}

// Apply parses a source file and appends new hosts to DestFile.
func Apply(opts Options) (Result, error) {
	if opts.Source == nil {
		return Result{}, fmt.Errorf("import source is required")
	}
	hosts, err := opts.Source.Parse(opts.Data)
	if err != nil {
		return Result{}, err
	}

	dest := opts.DestFile
	if dest == "" {
		dest = DefaultDestFile(opts.MainConfig, opts.Source.DestFileName())
	}

	existing, err := existingNames(opts.MainConfig, dest)
	if err != nil {
		return Result{}, err
	}

	var added []config.SSHHost
	skipped := 0
	for _, h := range hosts {
		if existing[h.Name] {
			skipped++
			continue
		}
		existing[h.Name] = true
		added = append(added, h)
	}

	preview := formatBlocks(added)
	res := Result{
		AddedCount:   len(added),
		SkippedCount: skipped,
		DestFile:     dest,
		Preview:      preview,
	}
	if opts.DryRun {
		return res, nil
	}

	if len(added) > 0 {
		if err := appendHosts(dest, opts.Source.Name(), added); err != nil {
			return Result{}, err
		}
	}
	addedInclude, err := ensureInclude(opts.MainConfig, dest)
	if err != nil {
		return Result{}, err
	}
	res.IncludeAdded = addedInclude
	return res, nil
}

func existingNames(mainConfig, destFile string) (map[string]bool, error) {
	names := map[string]bool{}
	collect := func(path string) error {
		if path == "" {
			return nil
		}
		hosts, err := config.ParseSSHConfigFile(path)
		if err != nil {
			return err
		}
		for _, h := range hosts {
			names[h.Name] = true
		}
		return nil
	}
	if err := collect(mainConfig); err != nil {
		return nil, err
	}
	if destFile != "" && destFile != mainConfig {
		if err := collect(destFile); err != nil {
			return nil, err
		}
	}
	return names, nil
}

func appendHosts(dest, sourceName string, hosts []config.SSHHost) error {
	if err := os.MkdirAll(filepath.Dir(dest), 0700); err != nil {
		return err
	}
	created := false
	if _, err := os.Stat(dest); os.IsNotExist(err) {
		created = true
	}
	f, err := os.OpenFile(dest, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0600)
	if err != nil {
		return err
	}
	defer f.Close()
	if created {
		header := fmt.Sprintf("# Generated by ctty from %s. Passwords are not copied.\n", sourceName)
		if _, err := f.WriteString(header); err != nil {
			return err
		}
	}
	if _, err := f.WriteString(formatBlocks(hosts)); err != nil {
		return err
	}
	return nil
}

func formatBlocks(hosts []config.SSHHost) string {
	var b strings.Builder
	for _, h := range hosts {
		b.WriteByte('\n')
		if len(h.Tags) > 0 {
			b.WriteString("# Tags: " + strings.Join(h.Tags, ", ") + "\n")
		}
		b.WriteString("Host " + h.Name + "\n")
		b.WriteString("    HostName " + h.Hostname + "\n")
		if h.User != "" {
			b.WriteString("    User " + h.User + "\n")
		}
		if h.Port != "" && h.Port != "22" {
			b.WriteString("    Port " + h.Port + "\n")
		}
		if h.Identity != "" {
			b.WriteString("    IdentityFile " + quoteIfNeeded(h.Identity) + "\n")
		}
		if h.ProxyJump != "" {
			b.WriteString("    ProxyJump " + h.ProxyJump + "\n")
		}
		if h.ProxyCommand != "" {
			b.WriteString("    ProxyCommand=" + h.ProxyCommand + "\n")
		}
		if h.Options != "" {
			for _, line := range strings.Split(h.Options, "\n") {
				line = strings.TrimSpace(line)
				if line != "" {
					b.WriteString("    " + line + "\n")
				}
			}
		}
	}
	return b.String()
}

func quoteIfNeeded(value string) string {
	if strings.Contains(value, " ") {
		return `"` + value + `"`
	}
	return value
}

func ensureInclude(mainConfig, destFile string) (bool, error) {
	if mainConfig == "" || destFile == "" {
		return false, nil
	}
	mainAbs, err := filepath.Abs(mainConfig)
	if err != nil {
		return false, err
	}
	destAbs, err := filepath.Abs(destFile)
	if err != nil {
		return false, err
	}
	rel, err := filepath.Rel(filepath.Dir(mainAbs), destAbs)
	if err != nil {
		rel = destAbs
	}
	rel = filepath.ToSlash(rel)

	body := []byte{}
	if _, err := os.Stat(mainAbs); err == nil {
		body, err = os.ReadFile(mainAbs)
		if err != nil {
			return false, err
		}
		if includeCovers(string(body), filepath.Dir(mainAbs), destAbs) {
			return false, nil
		}
	}

	includeLine := "Include " + rel + "\n"
	var out strings.Builder
	out.WriteString(includeLine)
	if len(body) > 0 && !strings.HasPrefix(string(body), "\n") {
		out.WriteByte('\n')
	}
	out.Write(body)

	if err := os.MkdirAll(filepath.Dir(mainAbs), 0700); err != nil {
		return false, err
	}
	if err := os.WriteFile(mainAbs, []byte(out.String()), 0600); err != nil {
		return false, err
	}
	return true, nil
}

func includeCovers(mainBody, mainDir, destAbs string) bool {
	for _, raw := range strings.Split(mainBody, "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 || !strings.EqualFold(fields[0], "Include") {
			continue
		}
		pattern := strings.Join(fields[1:], " ")
		expanded := expandIncludePattern(pattern, mainDir)
		if expanded == destAbs {
			return true
		}
		matches, err := filepath.Glob(expanded)
		if err != nil {
			continue
		}
		for _, m := range matches {
			abs, err := filepath.Abs(m)
			if err == nil && abs == destAbs {
				return true
			}
		}
		if filepath.Dir(expanded) == filepath.Dir(destAbs) {
			ok, err := filepath.Match(filepath.Base(expanded), filepath.Base(destAbs))
			if err == nil && ok {
				return true
			}
		}
	}
	return false
}

func expandIncludePattern(pattern, mainDir string) string {
	if strings.HasPrefix(pattern, "~") {
		home, err := os.UserHomeDir()
		if err == nil {
			rest := strings.TrimPrefix(pattern, "~")
			rest = strings.TrimPrefix(rest, "/")
			rest = strings.TrimPrefix(rest, string(os.PathSeparator))
			pattern = filepath.Join(home, rest)
		}
	}
	if !filepath.IsAbs(pattern) {
		pattern = filepath.Join(mainDir, pattern)
	}
	abs, err := filepath.Abs(pattern)
	if err != nil {
		return pattern
	}
	return abs
}
